name: Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Add current year label
        run: |
          YEAR=$(date +"%Y")
          echo "Adding label: $YEAR"
          gh pr edit "$PR_NUMBER" --add-label "$YEAR" --repo "$GITHUB_REPOSITORY"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Labeler
        uses: actions/labeler@v4
